name: Build Image

on:
  release:
    types: [ published ]

env:
  REGION: ${{secrets.GC_REGION }}
  GAR_LOCATION: ${{secrets.GAR_LOCATION}}

jobs:
  deploy:
    environment: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: google-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --tag ${{ env.GAR_LOCATION }}/django-test-service:${{ github.event.release.tag_name }}

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}/django-test-service:${{ github.event.release.tag_name }}